# Generated by Django 3.2.6 on 2021-08-25 09:04

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
                ('objects', users.models.MyUserManager()),
            ],
        ),
    ]
