# Generated by Django 3.2.6 on 2021-08-27 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import reservation.validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('start_time', models.DateTimeField(help_text='Enter the date of start', validators=[reservation.validator.min_time, reservation.validator.is_thirty_minutes], verbose_name='start date')),
                ('end_time', models.DateTimeField(help_text='Enter the date of end', validators=[reservation.validator.max_time, reservation.validator.is_thirty_minutes], verbose_name='end date')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
